=== Sales Input Event
Each time a PoS system processes a sales item an event with the following format is emitted:

.Sale Input Event
[width="100%",options="header"]
|====================
|Event| Fields | Description
| SALE_INPUT | time, sale_ID, amount, item_ID, quantity, assistant_ID, branch_ID, notes, ... |  Event indicating a sale of an item is occurring
|====================

In each `SALE_INPUT` event the `sale_ID` field is a unique ID generated by the PoS system.
A timestamp for the event is stored in the `time` field.
The `amount` field refers to the value of the item(s) to be sold (in cents).
The `item_ID` field is a unique identifier for each item type, and can be used to retrieve more information about the item from _HyperM_'s stock control system.
The `quantity` field refers to the quantity of the item to be sold.
The `assistant_ID` field is a unique identifier for the PoS operator, and can be used to retrieve more information about the operator from the _HyperM_'s personnel system.
Since __HyperM__ has many branches the `branch_ID` identifies the shop.
The `notes` field contains arbitrary notes about the sale.

