=== Test Policy Step 1

To start a new Apex Engine you can use the following _JSON_ link:files/mfp-files/1/config/MyFirstPolicyConfigStdin2StdoutJsonEvent.json[configuration file]. This configuration expects incoming events to be in `JSON` format and to be passed into the Apex Engine from `stdin`, and result events will be printed in `JSON` format to `stdout`. This configuration loads the policy model stored in the file 'MyFirstPolicyModel_0.0.1.json' as exported from the Apex Editor. Note, you may need to edit this file to provide the full path to wherever you stored the exported policy model file.

.JSON to load and execute _My First Policy_, read input JSON events from `stdin`, and emit output events to `stdout`
[source,json,options="nowrap"]
----
include::{apex-domains-myfirstpolicy-dir}/main/resources/com/ericsson/apex/domains/myfirstpolicy/1/config/MyFirstPolicyConfigStdin2StdoutJsonEvent.json[configuration file]
----

To test the policy try paste the following events into the console as the Apex engine executes:

.Inputs and Outputs when testing _My First Policy_
[width="100%",options="header",cols="4a,6a,2d"]
|====================
| Input Event (JSON) | Output Event (JSON) | comment
|
[source,json,options="nowrap"]
----
include::{apex-domains-myfirstpolicy-dir}/main/resources/examples/events/MyFirstPolicy/1/EventIn_NonBoozeItem_101309GMT.json[Input (`JSON`)]
----
|
[source,json,options="nowrap"]
----
include::{apex-domains-myfirstpolicy-dir}/main/resources/examples/events/MyFirstPolicy/1/EventOut_NonBoozeItem_101309GMT.json[Output (`JSON`)]
----
| Request to buy a non-alcoholic item (`item_ID=5123`) at _10:13:09_ on _Tuesday, 10 January 2017_.

Sale is authorized.

link:files/mfp-files/1/EventIn_NonBoozeItem_101309GMT.json[Input (`JSON`)]
link:files/mfp-files/1/EventOut_NonBoozeItem_101309GMT.json[Output (`JSON`)]
|
[source,json,options="nowrap"]
----
include::{apex-domains-myfirstpolicy-dir}/main/resources/examples/events/MyFirstPolicy/1/EventIn_BoozeItem_084106GMT.json[Input (`JSON`)]
----
|
[source,json,options="nowrap"]
----
include::{apex-domains-myfirstpolicy-dir}/main/resources/examples/events/MyFirstPolicy/1/EventOut_BoozeItem_084106GMT.json[Output (`JSON`)]
----
| Request to buy alcohol item (`item_ID=1249`) at _08:41:06_ on _Monday, 02 January 2017_.

Sale is not authorised.

link:files/mfp-files/1/EventIn_BoozeItem_084106GMT.json[Input (`JSON`)]
link:files/mfp-files/1/EventOut_BoozeItem_084106GMT.json[Output (`JSON`)]
|
[source,json,options="nowrap"]
----
include::{apex-domains-myfirstpolicy-dir}/main/resources/examples/events/MyFirstPolicy/1/EventIn_BoozeItem_201713GMT.json[Input (`JSON`)]
----
|
[source,json,options="nowrap"]
----
include::{apex-domains-myfirstpolicy-dir}/main/resources/examples/events/MyFirstPolicy/1/EventOut_BoozeItem_201713GMT.json[Output (`JSON`)]
----
| Request to buy alcohol (`item_ID=1943`) at _20:17:13_ on _Tuesday, 20 December 2016_.

Sale is authorised.

link:files/mfp-files/1/EventIn_BoozeItem_201713GMT.json[Input (`JSON`)]
link:files/mfp-files/1/EventOut_BoozeItem_201713GMT.json[Output (`JSON`)]
|====================

