== Dynamically Adaptive Policies (CNSM'15)

[width="100%",cols="15%,90%"]
|===

h| Title
e| Dynamically Adaptive Policies for Dynamically Adaptive Telecommunications Networks

h| Venue
| IEEE CNSM, Barcelona, November 2015

h| Abstract
| New technologies are changing the world of communication networks and even more so their management. Cloud computing and predictive analytics have removed the need for specialized compute hardware and created products that continuously search for and find insights in management data. Virtualization of networks and network functions, SDN and NFV, are beginning to be mature enough for production networks resulting in much more flexible and dynamic networks. IoT and M2M traffic and new customer demands are driving new thinking and demands for 5G networks. Almost every aspect in the control and management of networks has seen new dimensions of flexibility and dynamicity, with the notable exception of the policies that drive them. This paper discusses the need to add adaptiveness to classic policies, describes a novel approach for adaptive policies, shows how adaptive policies will form part of future network frameworks and architectures, and finally discusses early use cases developed for mobile operators.

h| Links
| link:https://www.researchgate.net/publication/282576518_Dynamically_Adaptive_Policies_for_Dynamically_Adaptive_Telecommunications_Networks[Research Gate] [accessed Aug 11, 2017]

h| BibTeX
a|
[source,bibtex]
----
@inproceedings{VanDerMeer2015c,
	Author = {van der Meer, S. and Keeney, J. and Fallon, L.},
	Booktitle = {Network and Service Management (CNSM), 2015 11th International Conference on},
	Doi = {10.1109/CNSM.2015.7367357},
	Keywords = {5G mobile communication;Internet of Things;cloud computing;telecommunication control;telecommunication traffic;virtualisation;5G networks;IoT;M2M traffic;NFV;SDN;cloud computing;communication networks;compute hardware;customer demands;dynamic networks;dynamically adaptive policies;dynamically adaptive telecommunications networks;flexible networks;management data;mobile operators;network architectures;network frameworks;network functions;network virtualization;predictive analytics;production networks;Decision support systems;Yttrium;Adaptive Policy;Automation;Control Loop;Policy},
	Month = {Nov},
	Pages = {182-186},
	Sequence = {c},
	Timestamp = {2015-09-21},
	Title = {{Dynamically Adaptive Policies for Dynamically Adaptive Telecommunications Networks}},
	Year = {2015},
	Bdsk-Url-1 = {http://dx.doi.org/10.1109/CNSM.2015.7367357}}
----

|===

