== Build with standard Tests

Use Maven to for a standard build with standard tests.

[IMPORTANT]
.Some tests have specific timing Requirements
====
Some of the tests have very specific timing requirements.
If run on a low-powered build machine, or if the build machine is on high load, those tests might fail and the whole build might fail as well.
If this happens, reduce the load on your build machine and restart the build.
====

[width="100%",options="header",cols="5a,5a"]
|====================
| Unix, Cygwin | Windows
|
[source%nowrap,sh,numbered]
----
# cd /usr/local/src/apex
# mvn clean install
----
|
[source%nowrap,bat,numbered]
----
>c:
>cd \dev\apex
>mvn clean install
----
|====================

The build takes about 5-6 minutes with tests on a standard development laptop.
It should run through without errors, but with a lot of messages from the build process.
If build with tests (i.e. without `-DskipTests`), there will be error messages and stack trace prints from some tests.
This is normal, as long as the build finishes successful.

When Maven is finished with the build, the final screen should look similar to this (omitting some `success` lines):

[source%nowrap,sh,numbered,subs="attributes+"]
----
include::{apex-main-dir}/docs/asciidoc/fragments/screens/mvn-install-skiptests.txt[mvn build, with tests]
----

The build will have created all artifacts required for an APEX installation.

